name: spacectl
namespace: spaceone
image:
    name: spaceone/spacectl
    version: latest
imagePullPolicy: IfNotPresent
replicas: 1

#imagePullSecret
# - {imagePullSecret_name}

#serviceAccountName: {name}

#env:
# - name: key
#   value: value

pvc:
    storageClassName: null # You must specify a storage class name. Otherwise, the spacectl pod will use empty volume.
    accessModes: 
        - "ReadWriteOnce"
    requests:
        storage: 8Gi